"""
src/hallucination.py — NLI claim verification (Novelty 2).

WHY THIS MODULE EXISTS:
The generator's prompt TELLS the LLM to answer only from the passages. This
module CHECKS whether it did. The answer is split into one-fact sentences
("claims"), and each claim is scored against the retrieved passages by a
Natural Language Inference cross-encoder that asks a single question:
"given this passage, does this claim follow?"

Without it, the system has no independent evidence that any sentence is
grounded — the only signal would be the citation markers, which are
themselves generated by the same model that might be hallucinating.

LEARN THIS — What NLI (Natural Language Inference) is:
NLI is a classic NLP task over a PAIR of texts: a PREMISE (evidence) and a
HYPOTHESIS (claim). The model outputs three probabilities:
  ENTAILMENT     — the premise supports the claim   ("grounded")
  NEUTRAL        — the premise neither supports nor refutes it ("unsupported")
  CONTRADICTION  — the premise refutes the claim    ("contradicted")
Note that NEUTRAL is the common hallucination case: the model invented a
plausible fact that simply is not in the document. It is not "false", it is
"not in evidence" — and for a medical assistant that is just as dangerous.

LEARN THIS — Direction matters:
NLI is NOT symmetric. (premise=passage, hypothesis=claim) asks "does the
document support this sentence?" — what we want. Flipping the arguments asks
"does this sentence support the document?", which is a different question and
scores very differently. Getting this backwards is a silent accuracy bug.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

import numpy as np                   # numpy: the probability matrix is small and
                                     # 2-D; numpy gives argmax/slicing without
                                     # keeping torch tensors alive past inference.

import torch                         # torch: runs the model's forward pass and
                                     # provides softmax over the raw logits.

from transformers import (           # transformers used DIRECTLY here, unlike the
    AutoModelForSequenceClassification,  # embedder which uses sentence-transformers.
    AutoTokenizer,                   # Reason: we need the raw 3-class logits, our own
)                                    # softmax, and the checkpoint's id2label mapping.
                                     # sentence-transformers' CrossEncoder hides all
                                     # three behind an activation-function argument
                                     # whose default changed between major versions.

from config import (
    NLI_BATCH_SIZE,
    NLI_CONTRADICTION_INDEX,
    NLI_ENTAILMENT_INDEX,
    NLI_ENTAILMENT_THRESHOLD,
    NLI_MAX_SEQ_LENGTH,
    NLI_MODEL_NAME,
)
from src.vectorstore import RetrievedChunk

if TYPE_CHECKING:                    # type hints only — see embedder.py for why
    from src.generator import GeneratedAnswer


# Claim status values. The Gradio UI maps these to colours:
# grounded = green, unsupported = amber, contradicted = red.
GROUNDED = "grounded"
UNSUPPORTED = "unsupported"
CONTRADICTED = "contradicted"

# A "sentence" shorter than this (in words, after citations are stripped) is
# not a checkable claim — it is a fragment like "See below" or a stray "[1]".
# Feeding it to the NLI model produces a meaningless score that would drag
# the groundedness percentage around for no reason.
_MIN_CLAIM_WORDS = 3


# ---------------------------------------------------------------------------
# CLAIM SPLITTING
# ---------------------------------------------------------------------------

# INTERVIEW ALERT — "How do you split an answer into checkable claims?"
#
# NAIVE APPROACH (don't do this):
#   claims = answer.split(".")
#   PROBLEM: medical text is made of decimals and abbreviations. "Give 0.5 mg
#   twice daily (e.g. with food)." becomes four fragments: "Give 0", "5 mg
#   twice daily (e", "g", " with food)". Every one of them scores as
#   unsupported, and the answer looks 100% hallucinated.
#
# BETTER APPROACH (what we do):
#   Split only where a sentence terminator is followed by whitespace AND the
#   next sentence actually begins (capital letter, digit, quote or bracket),
#   with negative lookbehinds for the abbreviations that appear in this
#   domain. "0.5" never matches because there is no space after the period.
#
# BEST APPROACH (not used here, worth knowing):
#   A trained sentence segmenter (spaCy, or nltk punkt) handles abbreviations
#   statistically instead of by list. We skip it because it adds a model
#   download for a job that a well-written regex does on LLM output, which is
#   already clean, well-punctuated prose. Say this trade-off out loud in an
#   interview — knowing WHY you didn't use the heavier tool is the answer.
# GOTCHA 1: each negative lookbehind must INCLUDE the final period. The split
# position sits AFTER the ".", so (?<!Fig) would inspect "ig." and never match.
# Caught by "See Fig. 2 for the curve." splitting into "See Fig." + "2 for...".
# GOTCHA 2: each guard needs a \b word boundary. Without it, the "et al." guard
# (?<!al\.) also fires on "meal." / "renal." / "clinical." and silently merges
# two sentences — caught on real NLI output, where a merged premise turned a
# verbatim-supported claim into "unsupported".
_SENTENCE_SPLIT_RE = re.compile(
    r"(?<!\be\.g\.)(?<!\bi\.e\.)(?<!\betc\.)(?<!\bvs\.)(?<!\bFig\.)(?<!\bDr\.)"
    r"(?<!\bal\.)"                                                     # abbrevs
    r"(?<=[.!?])"                                                     # terminator
    r"[\)\]\"']*\s+"                                                  # closers + space
    r"(?=[\"'(\[A-Z0-9])"                                             # next start
)

# Citation markers: "[1]", "[2][3]" (two matches), "[1, 2]". Same shape the
# generator writes and parses.
_CITATION_RE = re.compile(r"\[(\d+(?:\s*,\s*\d+)*)\]")


def split_sentences(text: str) -> list[str]:
    """
    Split answer text into sentences, citation markers still attached.

    Lines are separated first: an answer formatted as a bullet list has no
    terminal punctuation between items, so sentence splitting alone would
    return the entire list as one enormous claim.

    Args:
        text: Raw answer text from the LLM.

    Returns:
        Sentences in order, whitespace-trimmed, empties removed.
    """
    sentences: list[str] = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        sentences.extend(part.strip() for part in _SENTENCE_SPLIT_RE.split(line))
    return [s for s in sentences if s]


def strip_citations(sentence: str) -> str:
    """
    Remove "[n]" markers so the NLI model sees plain language.

    WHY THIS MATTERS:
    The NLI model was trained on ordinary sentence pairs. A trailing "[1]" is
    out-of-distribution noise that shifts the scores for no informational
    gain — the passage numbers are tracked separately on the claim.

    Args:
        sentence: A sentence that may contain citation markers.

    Returns:
        The sentence with markers removed and whitespace collapsed.
    """
    text = re.sub(r"\s+", " ", _CITATION_RE.sub("", sentence))
    # Removing a marker leaves "500 mg ." — close the gap so the claim reads
    # as ordinary prose, which is what the NLI model was trained on.
    return re.sub(r"\s+([.,;:!?)\]])", r"\1", text).strip()


def is_checkable(claim_text: str) -> bool:
    """
    Decide whether a citation-stripped sentence is worth scoring.

    Args:
        claim_text: Sentence with citations already removed.

    Returns:
        True if it has at least _MIN_CLAIM_WORDS words.
    """
    return len(claim_text.split()) >= _MIN_CLAIM_WORDS


# ---------------------------------------------------------------------------
# PREMISE SPLITTING
# ---------------------------------------------------------------------------

# INTERVIEW ALERT — "What granularity do you run NLI at, and why?"
# Answer: "Sentence level on BOTH sides. NLI models are trained on SNLI/MNLI,
# where the premise is one sentence. Feed a multi-sentence passage as the
# premise and entailment collapses unpredictably — in our own test, a claim
# copied VERBATIM from a passage's first sentence scored entailment 0.001
# against the full two-sentence passage, and 0.984 against that sentence
# alone. So each passage is split into sentences, the claim is scored against
# every one, and we keep the max. This is the idea behind SummaC
# (Laban et al., 2022), the standard method for NLI-based consistency checks."
#
# NAIVE APPROACH (what this module did first):
#   score(premise=whole_passage, hypothesis=claim)
#   PROBLEM: out-of-distribution premises; true facts come back "neutral",
#   so the UI would paint grounded sentences red. Nothing errors.
#
# BETTER APPROACH (what we do):
#   premises = every sentence of every passage + each whole passage.
#   The whole passage stays in the set for claims that need two sentences
#   combined (a dose in one sentence, its condition in the next).
#   COST: pairs grow from claims×passages to claims×sentences — roughly 5×.
#   Still one or two batched forward passes on a GPU; about a second on CPU.

# Region types whose line breaks are STRUCTURAL — one table row per line.
# Everywhere else a line break is only where the PDF column wrapped, often
# mid-sentence, so those lines are rejoined before sentence splitting.
_LINE_STRUCTURED_LABELS = {"table"}


def premise_units(passage: RetrievedChunk) -> list[str]:
    """
    Split one retrieved passage into the premises a claim is scored against.

    Prose regions: wrapped lines are rejoined, then split into sentences.
    Tables: each line (row) is its own premise. Rows are not filtered by
    length, because "Metformin 2000 mg" is a complete fact in a table.
    In both cases the whole passage is added last as a fallback.

    Args:
        passage: A chunk from the retriever.

    Returns:
        Unique, non-empty premise strings, sentences first, whole passage last.
    """
    lines = [ln.strip() for ln in passage.text.splitlines() if ln.strip()]
    if passage.region_label in _LINE_STRUCTURED_LABELS:
        units = lines
    else:
        sentences = (part.strip() for part in _SENTENCE_SPLIT_RE.split(" ".join(lines)))
        units = [sent for sent in sentences if is_checkable(sent)]
    units.append(passage.text.strip())
    return list(dict.fromkeys(u for u in units if u))    # dedupe, keep order


def build_premises(sources: list[RetrievedChunk]) -> tuple[list[str], np.ndarray]:
    """
    Flatten every passage into premises, remembering which passage each came from.

    Args:
        sources: Passages shown to the LLM, in citation order.

    Returns:
        (premise texts, owner) where owner[i] is the 0-based index into
        sources of the passage premise i was taken from.
    """
    texts: list[str] = []
    owner: list[int] = []
    for index, source in enumerate(sources):
        for unit in premise_units(source):
            texts.append(unit)
            owner.append(index)
    return texts, np.array(owner, dtype=int)


# ---------------------------------------------------------------------------
# DATA STRUCTURES
# ---------------------------------------------------------------------------

@dataclass
class VerifiedClaim:
    """
    One sentence of the answer, with its verdict against the evidence.

    Fields:
        text:           The claim, citation markers removed.
        cited:          Passage numbers the LLM cited for it (1-based).
        entailment:     Highest entailment probability over all passages.
        contradiction:  Highest contradiction probability over all passages.
        best_source:    1-based passage number that best supports it, or None
                        if there were no passages to check against.
        evidence:       The sentence (or table row) with the highest
                        entailment — what the UI shows as "supported by".
        counter_evidence: The premise with the highest contradiction. Shown
                        for CONTRADICTED claims so a reader can judge it:
                        NLI reads any differing number as contradiction, so
                        "Sitagliptin 100 mg" can "contradict" a claim about
                        a different drug. Showing the premise exposes that.
        status:         GROUNDED, UNSUPPORTED or CONTRADICTED.
        citation_ok:    True if a passage the LLM CITED is itself entailing.
                        False with status=GROUNDED means the fact is in the
                        document but the model pointed at the wrong passage.
    """
    text: str
    cited: list[int] = field(default_factory=list)
    entailment: float = 0.0
    contradiction: float = 0.0
    best_source: int | None = None
    evidence: str = ""
    counter_evidence: str = ""
    status: str = UNSUPPORTED
    citation_ok: bool = False

    @property
    def grounded(self) -> bool:
        """True if the evidence entails this claim."""
        return self.status == GROUNDED


@dataclass
class VerificationReport:
    """
    The verdict on a whole answer.

    Fields:
        question:  The user's question.
        answer:    The answer text that was checked.
        claims:    One VerifiedClaim per checkable sentence, in order.
        sources:   The passages the claims were checked against.
        abstained: True if the LLM declined to answer (nothing to verify).
        model:     NLI model used for the check.
    """
    question: str
    answer: str
    claims: list[VerifiedClaim]
    sources: list[RetrievedChunk]
    abstained: bool = False
    model: str = ""

    @property
    def groundedness(self) -> float:
        """
        Fraction of claims supported by the evidence, in [0, 1].

        Returns 1.0 when there are no claims: an abstention asserts nothing,
        so nothing about it is ungrounded.
        """
        if not self.claims:
            return 1.0
        return sum(c.grounded for c in self.claims) / len(self.claims)

    @property
    def flagged(self) -> list[VerifiedClaim]:
        """Claims the UI should highlight (unsupported or contradicted)."""
        return [c for c in self.claims if not c.grounded]


# ---------------------------------------------------------------------------
# CHECKER
# ---------------------------------------------------------------------------

class HallucinationChecker:
    """
    Verifies an LLM answer sentence-by-sentence against its own sources.

    WHY A CLASS: the model takes seconds to load, so load once and reuse —
    same reason as LayoutDetector and Embedder. app.py builds one and passes
    it around.

    Usage:
        checker = HallucinationChecker()
        report = checker.verify(generator.generate(question, hits))
        print(report.groundedness, [c.text for c in report.flagged])
    """

    def __init__(self, model_name: str = NLI_MODEL_NAME) -> None:
        """
        Load the NLI cross-encoder and work out its label order.

        Args:
            model_name: HuggingFace id of a 3-class NLI model.

        Raises:
            ValueError: If the checkpoint is not a 3-class classifier, which
                means it is not an NLI model and every score would be garbage.
        """
        print(f"[HallucinationChecker] Loading model: {model_name}")
        self.model_name = model_name
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSequenceClassification.from_pretrained(model_name)

        num_labels = self.model.config.num_labels
        if num_labels != 3:
            raise ValueError(
                f"'{model_name}' has {num_labels} output labels, expected 3 "
                f"(contradiction / neutral / entailment). This does not look "
                f"like an NLI model — check config.NLI_MODEL_NAME."
            )

        self.entail_idx, self.contra_idx = self._resolve_label_indices()
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model.to(self.device).eval()   # eval(): disables dropout — we are
                                            # doing inference, not training.
        print(f"[HallucinationChecker] Ready on {self.device}. "
              f"entailment={self.entail_idx}, contradiction={self.contra_idx}")

    def _resolve_label_indices(self) -> tuple[int, int]:
        """
        Read which output position means "entailment" from the checkpoint.

        WHY NOT JUST TRUST config.py:
        Label order differs between NLI model families (see the note on
        NLI_ENTAILMENT_INDEX in config.py). Hardcoding the wrong index does
        not raise — it reports neutral probabilities as entailment, so
        hallucinated claims quietly pass. The checkpoint knows its own label
        names, so we ask it and only fall back to config if it has none.

        Returns:
            (entailment index, contradiction index).
        """
        id2label = getattr(self.model.config, "id2label", None) or {}
        found: dict[str, int] = {}
        for idx, label in id2label.items():
            name = str(label).lower()
            if "entail" in name:
                found["entail"] = int(idx)
            elif "contradict" in name:
                found["contra"] = int(idx)

        if "entail" not in found:
            print(f"[HallucinationChecker] WARNING: '{self.model_name}' ships no "
                  f"usable label names ({id2label}); falling back to "
                  f"config.NLI_ENTAILMENT_INDEX={NLI_ENTAILMENT_INDEX}. "
                  f"Verify this against the model card before trusting scores.")
        return (found.get("entail", NLI_ENTAILMENT_INDEX),
                found.get("contra", NLI_CONTRADICTION_INDEX))

    # --- public API ---------------------------------------------------------

    def verify(self, answer: GeneratedAnswer) -> VerificationReport:
        """
        Check every claim in an answer against the passages it was given.

        Abstentions are returned unchecked: the not-found sentence makes no
        factual assertion, so there is nothing an NLI model could ground.

        Args:
            answer: A GeneratedAnswer from src/generator.py.

        Returns:
            A VerificationReport.

        Raises:
            RuntimeError: If the NLI forward pass fails.
        """
        if answer.abstained or not answer.sources:
            return VerificationReport(answer.question, answer.answer, [],
                                      answer.sources, abstained=True,
                                      model=self.model_name)

        claims = self._build_claims(answer.answer)
        if claims:
            premises, owner = build_premises(answer.sources)
            probs = self._score_claims(claims, premises)
            self._apply_scores(claims, probs, premises, owner)

        return VerificationReport(answer.question, answer.answer, claims,
                                  answer.sources, model=self.model_name)

    def score_pairs(self, premises: list[str], hypotheses: list[str]) -> np.ndarray:
        """
        Run the NLI model over (premise, hypothesis) pairs.

        WHY truncation="only_first":
        If a pair is too long, the EVIDENCE is cut, never the claim. Cutting
        the claim would change the very sentence being judged; cutting the
        evidence only costs the model some context.

        Args:
            premises:   Evidence texts (passages).
            hypotheses: Claim texts, same length as premises.

        Returns:
            Array of shape (n_pairs, 3) of probabilities per pair.

        Raises:
            ValueError:   If the two lists have different lengths.
            RuntimeError: If the forward pass fails.
        """
        if len(premises) != len(hypotheses):
            raise ValueError(
                f"score_pairs got {len(premises)} premises but "
                f"{len(hypotheses)} hypotheses — they must be parallel lists."
            )

        batches: list[np.ndarray] = []
        for start in range(0, len(premises), NLI_BATCH_SIZE):
            stop = start + NLI_BATCH_SIZE
            batches.append(self._forward(premises[start:stop], hypotheses[start:stop]))
        return np.vstack(batches) if batches else np.empty((0, 3))

    # --- internals ----------------------------------------------------------

    def _forward(self, premises: list[str], hypotheses: list[str]) -> np.ndarray:
        """
        One tokenize + forward + softmax pass over a single batch.

        Args:
            premises:   Evidence texts for this batch.
            hypotheses: Claim texts for this batch.

        Returns:
            Probabilities of shape (batch, 3).

        Raises:
            RuntimeError: If tokenization or the model call fails.
        """
        try:
            inputs = self.tokenizer(
                premises, hypotheses,              # pair order = (premise, hypothesis)
                padding=True,
                truncation="only_first",
                max_length=NLI_MAX_SEQ_LENGTH,
                return_tensors="pt",
            ).to(self.device)
            # inference_mode: no autograd graph is built — less memory, faster.
            with torch.inference_mode():
                logits = self.model(**inputs).logits
            # LEARN THIS — logits vs probabilities: the model's raw outputs are
            # unbounded scores. Softmax turns them into three numbers that sum
            # to 1, which is what a threshold like 0.5 is meaningful against.
            return torch.softmax(logits, dim=-1).cpu().numpy()
        except Exception as e:
            raise RuntimeError(
                f"NLI model '{self.model_name}' failed on a batch of "
                f"{len(premises)} pairs: {e}"
            ) from e

    def _build_claims(self, answer_text: str) -> list[VerifiedClaim]:
        """
        Turn answer text into the claims that will be scored.

        Args:
            answer_text: The LLM's answer, with citation markers.

        Returns:
            VerifiedClaim objects with text and cited filled in, scores not yet.
        """
        claims: list[VerifiedClaim] = []
        for sentence in split_sentences(answer_text):
            text = strip_citations(sentence)
            if not is_checkable(text):
                continue
            cited = sorted({int(n) for m in _CITATION_RE.finditer(sentence)
                            for n in m.group(1).split(",")})
            claims.append(VerifiedClaim(text=text, cited=cited))
        return claims

    def _score_claims(self, claims: list[VerifiedClaim], premises: list[str]) -> np.ndarray:
        """
        Score every claim against every premise in one batched run.

        INTERVIEW ALERT — "Why check a claim against ALL passages, not just
        the one it cites?" Answer: "The citation is model output too, so it
        can be wrong. Scoring against every passage separates two different
        failures: a fact that is nowhere in the document (a real
        hallucination) from a fact that IS in the document but cited to the
        wrong passage (a sloppy citation). Only the first is dangerous."

        Args:
            claims:   Claims to score.
            premises: Premise sentences from build_premises().

        Returns:
            Probabilities of shape (n_claims, n_premises, 3).
        """
        hyp_texts = [c.text for _ in premises for c in claims]
        prem_texts = [p for p in premises for _ in claims]
        flat = self.score_pairs(prem_texts, hyp_texts)
        # Built premise-major above, so reshape then swap to claim-major.
        return flat.reshape(len(premises), len(claims), 3).transpose(1, 0, 2)

    def _apply_scores(
        self,
        claims: list[VerifiedClaim],
        probs: np.ndarray,
        premises: list[str],
        owner: np.ndarray,
    ) -> None:
        """
        Fill in each claim's verdict from its scores against every premise.

        A claim is CONTRADICTED only if nothing entails it AND some premise
        actively refutes it — that ordering matters, because a document can
        contain both a supporting and a superseded statement.

        Args:
            claims:   Claims to update in place.
            probs:    Array of shape (n_claims, n_premises, 3).
            premises: Premise texts, parallel to probs' second axis.
            owner:    owner[i] = 0-based passage index of premise i.
        """
        for claim, claim_probs in zip(claims, probs):
            entail = claim_probs[:, self.entail_idx]
            contra = claim_probs[:, self.contra_idx]
            best, worst = int(entail.argmax()), int(contra.argmax())

            claim.entailment = float(entail[best])
            claim.contradiction = float(contra[worst])
            claim.best_source = int(owner[best]) + 1          # passages are 1-based
            claim.evidence = premises[best]
            claim.counter_evidence = premises[worst]
            if claim.entailment >= NLI_ENTAILMENT_THRESHOLD:
                claim.status = GROUNDED
            elif claim.contradiction >= NLI_ENTAILMENT_THRESHOLD:
                claim.status = CONTRADICTED
            else:
                claim.status = UNSUPPORTED

            supporting = {int(i) + 1 for i in owner[entail >= NLI_ENTAILMENT_THRESHOLD]}
            claim.citation_ok = any(n in supporting for n in claim.cited)
